Step1 return int
dhivelopers/r9cc pull request #2
Opened 2022-02-09 15:43 UTC by ainozaki

Changes:
- main.rs: 引数をそのままretに入れて返すアセンブラの出力
- test: test.sh作成

2022-02-09 15:47 UTC, uta8a requested changes
Reviewしました

2022-02-09 15:47 UTC, uta8a commented on src/main.rs
> +    let ret_value = env::args().nth(1).unwrap();
```rust
let ret_value = env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: ./r9cc <number>");
        process::exit(1);
    });
```

とかどうでしょう
unwrapだと、引数ないときにpanicメッセージでちゃって優しくないので

2022-02-09 15:49 UTC, uta8a commented on src/main.rs
> +    let ret_value = env::args().nth(1).unwrap();
`use std::env::process` のインポートが必要です

2022-02-09 16:03 UTC, uta8a approved these changes
よさそう

2022-02-09 16:05 UTC, merged

2022-02-09 21:40 UTC, hppRC commented on src/main.rs
> +    println!("\tmov rax, {}", ret_value);
Rust 1.58 から `println!("\tmov rax, {ret_value}");` のように書けるようになってるはずなので、手元の環境がRust 1.58までアップデートしてあれば、そうするのが簡潔かもしれない
https://tech-blog.optim.co.jp/entry/2022/01/14/080000

2022-02-09 21:41 UTC, hppRC commented on src/main.rs
> +    println!("\tmov rax, {}", ret_value);
というわけでこう
```suggestion
    println!("\tmov rax, {ret_value}");
```

2022-02-10 00:54 UTC, ainozaki commented on src/main.rs
> +    println!("\tmov rax, {}", ret_value);
fixed!!!!
ありがとう:smile: